version: '3'

services:
  app: &default
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: "django-insecure-uc(57i0mqby-egi&ns_(rj(uh-smif4^jaum#a06&ly5xbq4_s"
      DATABASE_URL: "postgresql://simon@host.docker.internal/shoppinglist"
      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""
      AWS_STORAGE_BUCKET_NAME: ""
      CORS_ALLOWED_ORIGINS: '"http://192.168.1.6:19006","http://localhost:19006"'
    command: sh -c "
      python manage.py collectstatic --no-input &&
      gunicorn project.wsgi --bind 0.0.0.0:8000 --workers 2 --log-file - --access-logfile - --log-level debug"
  test: &test
    <<: *default
    environment:
      SECRET_KEY: "django-insecure-uc(57i0mqby-egi&ns_(rj(uh-smif4^jaum#a06&ly5xbq4_s"
      DATABASE_URL: "sqlite:////tmp/test.sqlite"
      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""
      AWS_STORAGE_BUCKET_NAME: ""
      CORS_ALLOWED_ORIGINS: "http://localhost"
    command: python manage.py test
