name: Linters

on:
  pull_request:
    paths:
      - 'backend/**'
  push:
    paths:
      - 'backend/**'
    branches:
      - master

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: black
        uses: psf/black@stable
  djhtml:
    name: djhtml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: pip3 install djhtml
      - name: Run docformatter
        run: find -name "*.html" | xargs djhtml -t 2 -c
        working-directory: .
