name: Migrate

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-west-1
  ECS_CLUSTER: shoppinglist-cluster

jobs:
  Migrate:
    name: Run migrations
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # get subnets
    # aws ec2 describe-subnets --filters Name=tag:aws:cloudformation:stack-name,Values=EC2ContainerService-shoppinglist-cluster | jq -r '.Subnets | map(.SubnetId) | join(",")'

    - name: Build and tag image
      run: |
        aws ecs run-task \
        --cluster $ECS_CLUSTER \
        --task-definition shoppinglist-app-task \
        --overrides file://.aws/run_task_migrate.json \
        --count 1 \
        --launch-type FARGATE \
        --network-configuration "awsvpcConfiguration={subnets=[subnet-0f0fc49bb06e8a410,subnet-06b2e94a1505c7050],assignPublicIp=ENABLED}"
